class ValidatorEphemeralException(Exception): ...


class ValidatorCriticalException(Exception): ...


class VolaraApiServerException(ValidatorEphemeralException): ...


class TwitterScrapeException(ValidatorEphemeralException): ...
